/*==============================================================*/
/* Table: GSMP_LOC_GRIDS                                        */
/*==============================================================*/
CREATE TABLE GSMP_LOC_GRIDS
(
  ID                  NUMBER(22)    NOT NULL,
  NAME                VARCHAR2(128) NOT NULL,
  CODE                VARCHAR2(16)  NOT NULL,
  LVL                 NUMBER(2),
  GRID_TYPE           VARCHAR2(16),
  DESCRIPITON         VARCHAR2(256),
  DUTY_PHONE          VARCHAR2(32),
  PHOTO_URL           VARCHAR2(256),
  MEMBER_NUM          NUMBER(6),
  HOUSEHOLDE_NUM      NUMBER(6),
  AREA                NUMBER(8, 2),
  PARENT_ID           NUMBER(22),
  ADMIN_DIVISION_CODE VARCHAR2(20),
  ADMIN_DIVISION      VARCHAR2(128),
  MANUAL_SN           NUMBER(4),
  GEO_OUTLINE_ID      NUMBER(22),
  TIME_CREATED        TIMESTAMP,
  LAST_MODIFIED       TIMESTAMP,
  ENABLED             NUMBER(2)     NOT NULL,
  CONSTRAINT PK_GSMP_LOC_GRIDS PRIMARY KEY (ID)
);

COMMENT ON TABLE GSMP_LOC_GRIDS IS
'网格信息(基本)';

COMMENT ON COLUMN GSMP_LOC_GRIDS.ID IS
'网格ID';

COMMENT ON COLUMN GSMP_LOC_GRIDS.CODE IS
'网格编码';

COMMENT ON COLUMN GSMP_LOC_GRIDS.LVL IS
'网格层级';

COMMENT ON COLUMN GSMP_LOC_GRIDS.NAME IS
'网格名称';

COMMENT ON COLUMN GSMP_LOC_GRIDS.GRID_TYPE IS
'网格类型编码';

COMMENT ON COLUMN GSMP_LOC_GRIDS.DESCRIPITON IS
'描述';

COMMENT ON COLUMN GSMP_LOC_GRIDS.DUTY_PHONE IS
'值班电话';

COMMENT ON COLUMN GSMP_LOC_GRIDS.PHOTO_URL IS
'网格图片';

COMMENT ON COLUMN GSMP_LOC_GRIDS.MEMBER_NUM IS
'网格员数量';

COMMENT ON COLUMN GSMP_LOC_GRIDS.HOUSEHOLDE_NUM IS
'网格户数';

COMMENT ON COLUMN GSMP_LOC_GRIDS.AREA IS
'网格面积（平方米）';

COMMENT ON COLUMN GSMP_LOC_GRIDS.PARENT_ID IS
'上级网格ID';

COMMENT ON COLUMN GSMP_LOC_GRIDS.ADMIN_DIVISION_CODE IS
'隶属行政区划编码';

COMMENT ON COLUMN GSMP_LOC_GRIDS.ADMIN_DIVISION IS
'隶属行政区划';

COMMENT ON COLUMN GSMP_LOC_GRIDS.MANUAL_SN IS
'手动排序';

COMMENT ON COLUMN GSMP_LOC_GRIDS.GEO_OUTLINE_ID IS
'轮廓ID';

COMMENT ON COLUMN GSMP_LOC_GRIDS.TIME_CREATED IS
'创建时间';

COMMENT ON COLUMN GSMP_LOC_GRIDS.LAST_MODIFIED IS
'最后变更时间';

COMMENT ON COLUMN GSMP_LOC_GRIDS.ENABLED IS
'可用状态(1:正常 0:冻结)';

/*==============================================================*/
/* Table: GSMP_LOC_GRID_TYPES                                   */
/*==============================================================*/
CREATE TABLE GSMP_LOC_GRID_TYPES
(
  ID            NUMBER(22)    NOT NULL,
  NAME          VARCHAR2(128) NOT NULL,
  CODE          VARCHAR2(16)  NOT NULL,
  DESCRIPITON   VARCHAR2(256),
  TIME_CREATED  TIMESTAMP,
  LAST_MODIFIED TIMESTAMP,
  CONSTRAINT PK_GSMP_LOC_GRID_TYPES PRIMARY KEY (ID)
);

COMMENT ON TABLE GSMP_LOC_GRID_TYPES IS
'网格类型';

COMMENT ON COLUMN GSMP_LOC_GRID_TYPES.ID IS
'网格类型ID';

COMMENT ON COLUMN GSMP_LOC_GRID_TYPES.CODE IS
'网格类型编码';

COMMENT ON COLUMN GSMP_LOC_GRID_TYPES.NAME IS
'网格类型名称';

COMMENT ON COLUMN GSMP_LOC_GRID_TYPES.DESCRIPITON IS
'描述';

COMMENT ON COLUMN GSMP_LOC_GRID_TYPES.TIME_CREATED IS
'创建时间';

COMMENT ON COLUMN GSMP_LOC_GRID_TYPES.LAST_MODIFIED IS
'最后变更时间';

/*==============================================================*/
/* Table: USMS_APPLICATIONS                                     */
/*==============================================================*/
CREATE TABLE USMS_APPLICATIONS
(
  ID            NUMBER(22)    NOT NULL,
  CLIENT_ID     VARCHAR2(128) NOT NULL,
  CLIENT_SECRET VARCHAR2(128) NOT NULL,
  LABEL         VARCHAR2(128) NOT NULL,
  NAME          VARCHAR2(128) NOT NULL,
  CLIENT_URI    VARCHAR2(512),
  REDIRECT_URI  VARCHAR2(512),
  LOGOUT_URI    VARCHAR2(512),
  LOGO_URI      VARCHAR2(512),
  CLIENT_DESC   VARCHAR2(1024),
  ENABLED       NUMBER(2)     NOT NULL,
  CONSTRAINT PK_USMS_APPLICATIONS PRIMARY KEY (ID)
);

COMMENT ON TABLE USMS_APPLICATIONS IS
'统一用户管理-接入应用信息';

COMMENT ON COLUMN USMS_APPLICATIONS.ID IS
'标识';

COMMENT ON COLUMN USMS_APPLICATIONS.CLIENT_ID IS
'唯一标识码';

COMMENT ON COLUMN USMS_APPLICATIONS.CLIENT_SECRET IS
'接入应用密码';

COMMENT ON COLUMN USMS_APPLICATIONS.LABEL IS
'接入应用名称';

COMMENT ON COLUMN USMS_APPLICATIONS.NAME IS
'接入应用编码';

COMMENT ON COLUMN USMS_APPLICATIONS.CLIENT_URI IS
'接入应用首页地址';

COMMENT ON COLUMN USMS_APPLICATIONS.REDIRECT_URI IS
'接入应用验证回调地址';

COMMENT ON COLUMN USMS_APPLICATIONS.LOGOUT_URI IS
'接入应用登出地址，用于单点登出';

COMMENT ON COLUMN USMS_APPLICATIONS.LOGO_URI IS
'接入应用图标地址';

COMMENT ON COLUMN USMS_APPLICATIONS.CLIENT_DESC IS
'接入应用描述';

COMMENT ON COLUMN USMS_APPLICATIONS.ENABLED IS
'可用状态(1:正常 0:冻结)';

/*==============================================================*/
/* Table: USMS_INSTITUTIONS                                     */
/*==============================================================*/
CREATE TABLE USMS_INSTITUTIONS
(
  ID                    NUMBER(22)    NOT NULL,
  LABEL                 VARCHAR2(128) NOT NULL,
  NAME                  VARCHAR2(128) NOT NULL,
  TREE_LEVEL            NUMBER(4),
  PARENT_ID             NUMBER(22),
  PATH                  VARCHAR2(4000),
  TYPE                  NUMBER(1),
  MANUAL_SN             NUMBER(4),
  ADMIN_DIVISION_CODE   VARCHAR2(20),
  ADMIN_DIVISION        VARCHAR2(128),
  ENABLED               NUMBER(2)     NOT NULL,
  SOCIAL_CREDIT_UNICODE VARCHAR2(18),
  ORG_CODE              VARCHAR2(64),
  TIME_CREATED          TIMESTAMP,
  CREATOR_ID            NUMBER(22),
  LAST_MODIFIED         TIMESTAMP,
  MODIFIER_ID           NUMBER(22),
  CREATOR               VARCHAR2(64),
  MODIFIER              VARCHAR2(64),
  CONSTRAINT PK_USMS_INSTITUTIONS PRIMARY KEY (ID)
);

COMMENT ON TABLE USMS_INSTITUTIONS IS
'统一用户管理-组织机构信息表';

COMMENT ON COLUMN USMS_INSTITUTIONS.ID IS
'机构ID';

COMMENT ON COLUMN USMS_INSTITUTIONS.LABEL IS
'组织机构名称';

COMMENT ON COLUMN USMS_INSTITUTIONS.NAME IS
'组织机构编码';

COMMENT ON COLUMN USMS_INSTITUTIONS.TREE_LEVEL IS
'树形等级';

COMMENT ON COLUMN USMS_INSTITUTIONS.PARENT_ID IS
'父机构ID';

COMMENT ON COLUMN USMS_INSTITUTIONS.PATH IS
'树形路径';

COMMENT ON COLUMN USMS_INSTITUTIONS.TYPE IS
'类型 1:机构 2:部门';

COMMENT ON COLUMN USMS_INSTITUTIONS.MANUAL_SN IS
'手动排序';

COMMENT ON COLUMN USMS_INSTITUTIONS.ADMIN_DIVISION_CODE IS
'行政区划代码';

COMMENT ON COLUMN USMS_INSTITUTIONS.ADMIN_DIVISION IS
'行政区划';

COMMENT ON COLUMN USMS_INSTITUTIONS.ENABLED IS
'可用状态(1:正常 0:冻结)';

COMMENT ON COLUMN USMS_INSTITUTIONS.SOCIAL_CREDIT_UNICODE IS
'社会信用统一代码';

COMMENT ON COLUMN USMS_INSTITUTIONS.ORG_CODE IS
'组织机构代码';

COMMENT ON COLUMN USMS_INSTITUTIONS.TIME_CREATED IS
'创建时间';

COMMENT ON COLUMN USMS_INSTITUTIONS.CREATOR_ID IS
'创建人ID';

COMMENT ON COLUMN USMS_INSTITUTIONS.LAST_MODIFIED IS
'更新时间';

COMMENT ON COLUMN USMS_INSTITUTIONS.MODIFIER_ID IS
'更新人ID';

COMMENT ON COLUMN USMS_INSTITUTIONS.CREATOR IS
'创建人';

COMMENT ON COLUMN USMS_INSTITUTIONS.MODIFIER IS
'更新人';

/*==============================================================*/
/* Table: USMS_OPERATIONS                                       */
/*==============================================================*/
CREATE TABLE USMS_OPERATIONS
(
  ID             NUMBER(22)    NOT NULL,
  LABEL          VARCHAR2(128) NOT NULL,
  NAME           VARCHAR2(128) NOT NULL,
  MANUAL_SN      NUMBER(4),
  PARENT_ID      NUMBER(22),
  TREE_LEVEL     NUMBER(4),
  PATH           VARCHAR2(4000),
  RES_URL        VARCHAR2(256),
  ICON_PATH      VARCHAR2(128),
  OPT_TYPE       NUMBER(2)     NOT NULL,
  ENABLED        NUMBER(2),
  APPLICATION_ID NUMBER(22),
  CONSTRAINT PK_USMS_OPERATIONS PRIMARY KEY (ID)
);

COMMENT ON TABLE USMS_OPERATIONS IS
'统一用户管理-系统操作项表';

COMMENT ON COLUMN USMS_OPERATIONS.ID IS
'操作ID';

COMMENT ON COLUMN USMS_OPERATIONS.LABEL IS
'操作名称';

COMMENT ON COLUMN USMS_OPERATIONS.NAME IS
'操作编码';

COMMENT ON COLUMN USMS_OPERATIONS.MANUAL_SN IS
'手动排序';

COMMENT ON COLUMN USMS_OPERATIONS.PARENT_ID IS
'父亲ID';

COMMENT ON COLUMN USMS_OPERATIONS.TREE_LEVEL IS
'树形层级';

COMMENT ON COLUMN USMS_OPERATIONS.PATH IS
'树形路径';

COMMENT ON COLUMN USMS_OPERATIONS.RES_URL IS
'操作URL';

COMMENT ON COLUMN USMS_OPERATIONS.ICON_PATH IS
'操作图标路径';

COMMENT ON COLUMN USMS_OPERATIONS.OPT_TYPE IS
'操作类型(1:菜单 2:按钮)';

COMMENT ON COLUMN USMS_OPERATIONS.ENABLED IS
'可用状态(1:正常 0:冻结)';

COMMENT ON COLUMN USMS_OPERATIONS.APPLICATION_ID IS
'应用ID';

/*==============================================================*/
/* Table: USMS_PRIVILEGES                                       */
/*==============================================================*/
CREATE TABLE USMS_PRIVILEGES
(
  ID      NUMBER(22)    NOT NULL,
  LABEL   VARCHAR2(128) NOT NULL,
  NAME    VARCHAR2(128) NOT NULL,
  ENABLED NUMBER(2)     NOT NULL,
  REMARKS VARCHAR2(512),
  CONSTRAINT PK_USMS_PRIVILEGES PRIMARY KEY (ID)
);

COMMENT ON TABLE USMS_PRIVILEGES IS
'统一用户管理-权限信息表';

COMMENT ON COLUMN USMS_PRIVILEGES.ID IS
'权限ID';

COMMENT ON COLUMN USMS_PRIVILEGES.LABEL IS
'权限名称';

COMMENT ON COLUMN USMS_PRIVILEGES.NAME IS
'权限编码';

COMMENT ON COLUMN USMS_PRIVILEGES.ENABLED IS
'可用状态(1:正常 0:冻结)';

COMMENT ON COLUMN USMS_PRIVILEGES.REMARKS IS
'备注';

/*==============================================================*/
/* Table: USMS_PRIVILEGE_OPERATION                              */
/*==============================================================*/
CREATE TABLE USMS_PRIVILEGE_OPERATION
(
  PRIV_ID NUMBER(22) NOT NULL,
  OPER_ID NUMBER(22) NOT NULL
);

COMMENT ON TABLE USMS_PRIVILEGE_OPERATION IS
'统一用户管理-权限操作关系表';

COMMENT ON COLUMN USMS_PRIVILEGE_OPERATION.PRIV_ID IS
'权限ID';

COMMENT ON COLUMN USMS_PRIVILEGE_OPERATION.OPER_ID IS
'功能ID';

/*==============================================================*/
/* Table: USMS_PRIVILEGE_ROLE                                   */
/*==============================================================*/
CREATE TABLE USMS_PRIVILEGE_ROLE
(
  PRIV_ID NUMBER(22) NOT NULL,
  ROLE_ID NUMBER(22) NOT NULL
);

COMMENT ON TABLE USMS_PRIVILEGE_ROLE IS
'统一用户管理-权限角色关系表';

COMMENT ON COLUMN USMS_PRIVILEGE_ROLE.PRIV_ID IS
'权限ID';

COMMENT ON COLUMN USMS_PRIVILEGE_ROLE.ROLE_ID IS
'角色ID';

/*==============================================================*/
/* Table: USMS_ROLES                                            */
/*==============================================================*/
CREATE TABLE USMS_ROLES
(
  ID      NUMBER(22)    NOT NULL,
  LABEL   VARCHAR2(128) NOT NULL,
  NAME    VARCHAR2(128) NOT NULL,
  ENABLED NUMBER(2)     NOT NULL,
  REMARKS VARCHAR2(512),
  CONSTRAINT PK_USMS_ROLES PRIMARY KEY (ID)
);

COMMENT ON TABLE USMS_ROLES IS
'统一用户管理-系统角色表';

COMMENT ON COLUMN USMS_ROLES.ID IS
'角色ID';

COMMENT ON COLUMN USMS_ROLES.LABEL IS
'角色名称';

COMMENT ON COLUMN USMS_ROLES.NAME IS
'角色编码';

COMMENT ON COLUMN USMS_ROLES.ENABLED IS
'可用状态(1:正常 0:冻结)';

COMMENT ON COLUMN USMS_ROLES.REMARKS IS
'备注';

/*==============================================================*/
/* Table: USMS_STAFFS                                           */
/*==============================================================*/
CREATE TABLE USMS_STAFFS
(
  ID                  NUMBER(22) NOT NULL,
  NAME                VARCHAR2(64),
  TEL                 VARCHAR2(32),
  MOBILE              VARCHAR2(32),
  ZIP_CODE            VARCHAR2(32),
  EMAIL               VARCHAR2(64),
  EXTRANET_EMAIL      VARCHAR2(64),
  ALIAS_NAMES         VARCHAR2(64),
  SEX                 NUMBER(2),
  PICTURE_URL         VARCHAR2(256),
  PROFESSIONAL_TITLE  VARCHAR2(64),
  OFFICAL_POST        VARCHAR2(64),
  OFFICAL_DUTY        VARCHAR2(64),
  EMPLOYEE_TYPE       VARCHAR2(64),
  EMPLOYEE_NO         VARCHAR2(64),
  CITIZEN_ID_NUMBER   VARCHAR2(18),
  BIRTHDAY            DATE,
  ADMIN_DIVISION_CODE VARCHAR2(18),
  ADMIN_DIVISION      VARCHAR2(128),
  CUR_RESIDENCE       VARCHAR2(512),
  REMARKS             VARCHAR2(512),
  LAST_MODIFIED       TIMESTAMP,
  MODIFIER_ID         NUMBER(22),
  MODIFIER            VARCHAR2(64),
  TIME_CREATED        TIMESTAMP,
  CREATOR_ID          NUMBER(22),
  CREATOR             VARCHAR2(64),
  CONSTRAINT PK_USMS_STAFFS PRIMARY KEY (ID)
);

COMMENT ON TABLE USMS_STAFFS IS
'统一用户管理-员工信息表';

COMMENT ON COLUMN USMS_STAFFS.ID IS
'员工ID';

COMMENT ON COLUMN USMS_STAFFS.NAME IS
'员工姓名';

COMMENT ON COLUMN USMS_STAFFS.TEL IS
'固定电话号';

COMMENT ON COLUMN USMS_STAFFS.MOBILE IS
'手机号码';

COMMENT ON COLUMN USMS_STAFFS.ZIP_CODE IS
'邮编';

COMMENT ON COLUMN USMS_STAFFS.EMAIL IS
'内网邮箱';

COMMENT ON COLUMN USMS_STAFFS.EXTRANET_EMAIL IS
'外网邮箱';

COMMENT ON COLUMN USMS_STAFFS.ALIAS_NAMES IS
'别名,多个用逗号隔开';

COMMENT ON COLUMN USMS_STAFFS.PICTURE_URL IS
'照片URL';

COMMENT ON COLUMN USMS_STAFFS.SEX IS
'性别(1:男 2:女)';

COMMENT ON COLUMN USMS_STAFFS.PROFESSIONAL_TITLE IS
'职称';

COMMENT ON COLUMN USMS_STAFFS.OFFICAL_POST IS
'职务';

COMMENT ON COLUMN USMS_STAFFS.OFFICAL_DUTY IS
'职责';

COMMENT ON COLUMN USMS_STAFFS.EMPLOYEE_TYPE IS
'员工类别';

COMMENT ON COLUMN USMS_STAFFS.EMPLOYEE_NO IS
'员工工号';

COMMENT ON COLUMN USMS_STAFFS.CITIZEN_ID_NUMBER IS
'身份证号码';

COMMENT ON COLUMN USMS_STAFFS.BIRTHDAY IS
'出生日期';

COMMENT ON COLUMN USMS_STAFFS.ADMIN_DIVISION_CODE IS
'居住地行政区划编号';

COMMENT ON COLUMN USMS_STAFFS.ADMIN_DIVISION IS
'居住地行政区划';

COMMENT ON COLUMN USMS_STAFFS.CUR_RESIDENCE IS
'现居住地址';

COMMENT ON COLUMN USMS_STAFFS.REMARKS IS
'备注说明';

COMMENT ON COLUMN USMS_STAFFS.LAST_MODIFIED IS
'更新时间';

COMMENT ON COLUMN USMS_STAFFS.MODIFIER_ID IS
'更新人ID';

COMMENT ON COLUMN USMS_STAFFS.MODIFIER IS
'更新人';

COMMENT ON COLUMN USMS_STAFFS.TIME_CREATED IS
'创建时间';

COMMENT ON COLUMN USMS_STAFFS.CREATOR_ID IS
'创建人ID';

COMMENT ON COLUMN USMS_STAFFS.CREATOR IS
'创建人';

/*==============================================================*/
/* Table: USMS_STAFF_INSTITUTION                                */
/*==============================================================*/
CREATE TABLE USMS_USER_INSTITUTION
(
  USER_ID  NUMBER(22) NOT NULL,
  INSTITUTION_ID NUMBER(22) NOT NULL
);

COMMENT ON TABLE USMS_USER_INSTITUTION IS
'统一用户管理-用户组织机构关系表';

COMMENT ON COLUMN USMS_USER_INSTITUTION.INSTITUTION_ID IS
'组织机构ID';

COMMENT ON COLUMN USMS_USER_INSTITUTION.USER_ID IS
'用户ID';

/*==============================================================*/
/* Table: USMS_USERS                                            */
/*==============================================================*/
CREATE TABLE USMS_USERS
(
  ID            NUMBER(22)   NOT NULL,
  LOGIN_NAME    VARCHAR2(64) NOT NULL,
  PASSWORD      VARCHAR2(64) NOT NULL,
  SALT          VARCHAR2(64),
  NAME          VARCHAR2(64),
  USER_NO       VARCHAR2(64),
  ENABLED       NUMBER(2)    NOT NULL,
  STAFF_ID      NUMBER(22),
  REMARKS       VARCHAR2(512),
  PWD_MODIFIED  TIMESTAMP,
  LAST_MODIFIED TIMESTAMP,
  MODIFIER_ID   NUMBER(22),
  MODIFIER      VARCHAR2(64),
  TIME_CREATED  TIMESTAMP    NOT NULL,
  CREATOR_ID    NUMBER(22),
  CREATOR       VARCHAR2(64),
  CONSTRAINT PK_USMS_USERS PRIMARY KEY (ID)
);

COMMENT ON TABLE USMS_USERS IS
'统一用户管理-系统用户表';

COMMENT ON COLUMN USMS_USERS.ID IS
'用户ID';

COMMENT ON COLUMN USMS_USERS.LOGIN_NAME IS
'登录名';

COMMENT ON COLUMN USMS_USERS.PASSWORD IS
'密码';

COMMENT ON COLUMN USMS_USERS.USER_NO IS
'用户编号';

COMMENT ON COLUMN USMS_USERS.SALT IS
'加密盐值';

COMMENT ON COLUMN USMS_USERS.NAME IS
'姓名';

COMMENT ON COLUMN USMS_USERS.ENABLED IS
'可用状态(1:正常 0:冻结)';

COMMENT ON COLUMN USMS_USERS.STAFF_ID IS
'关联员工ID';

COMMENT ON COLUMN USMS_USERS.REMARKS IS
'备注说明';

COMMENT ON COLUMN USMS_USERS.PWD_MODIFIED IS
'最后修改密码日期';

COMMENT ON COLUMN USMS_USERS.LAST_MODIFIED IS
'更新时间';

COMMENT ON COLUMN USMS_USERS.MODIFIER_ID IS
'更新人ID';

COMMENT ON COLUMN USMS_USERS.MODIFIER IS
'更新人';

COMMENT ON COLUMN USMS_USERS.TIME_CREATED IS
'创建时间';

COMMENT ON COLUMN USMS_USERS.CREATOR_ID IS
'创建人ID';

COMMENT ON COLUMN USMS_USERS.CREATOR IS
'创建人';

/*==============================================================*/
/* Table: USMS_USER_ROLE                                        */
/*==============================================================*/
CREATE TABLE USMS_USER_ROLE
(
  ROLE_ID NUMBER(22) NOT NULL,
  USER_ID NUMBER(22) NOT NULL
);

COMMENT ON TABLE USMS_USER_ROLE IS
'统一用户管理-用户角色关系表';

COMMENT ON COLUMN USMS_USER_ROLE.ROLE_ID IS
'角色ID';

COMMENT ON COLUMN USMS_USER_ROLE.USER_ID IS
'用户ID';

/*==============================================================*/
/* Table: USMS_USER_GRID                                        */
/*==============================================================*/
CREATE TABLE USMS_USER_GRID (
  USER_ID   NUMBER(22) NOT NULL,
  GRID_CODE NVARCHAR2(16)
);

COMMENT ON TABLE USMS_USER_GRID
IS '统一用户管理-用户网格关系表';

COMMENT ON COLUMN USMS_USER_GRID.USER_ID IS '用户ID';

COMMENT ON COLUMN USMS_USER_GRID.GRID_CODE IS '网格CODE';

-- Create/Recreate foreign key constraints

ALTER TABLE USMS_OPERATIONS
  ADD CONSTRAINT FK_USMS_OPERATIONS_APP_ID FOREIGN KEY (APPLICATION_ID)
REFERENCES USMS_APPLICATIONS (ID) ON DELETE CASCADE;

ALTER TABLE USMS_PRIVILEGE_OPERATION
  ADD CONSTRAINT FK_USMS_PRIV_OPER_OPER_ID FOREIGN KEY (OPER_ID)
REFERENCES USMS_OPERATIONS (ID) ON DELETE CASCADE;

ALTER TABLE USMS_PRIVILEGE_OPERATION
  ADD CONSTRAINT FK_USMS_PRIV_OPER_PRIV_ID FOREIGN KEY (PRIV_ID)
REFERENCES USMS_PRIVILEGES (ID) ON DELETE CASCADE;

ALTER TABLE USMS_PRIVILEGE_ROLE
  ADD CONSTRAINT FK_USMS_PRIV_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID)
REFERENCES USMS_ROLES (ID) ON DELETE CASCADE;

ALTER TABLE USMS_PRIVILEGE_ROLE
  ADD CONSTRAINT FK_USMS_PRIV_ROLE_PRIV_ID FOREIGN KEY (PRIV_ID)
REFERENCES USMS_PRIVILEGES (ID) ON DELETE CASCADE;

ALTER TABLE USMS_USERS
  ADD CONSTRAINT FK_USMS_USERS_STAFFS_ID FOREIGN KEY (STAFF_ID)
REFERENCES USMS_STAFFS (ID) ON DELETE CASCADE;

ALTER TABLE USMS_USER_INSTITUTION
  ADD CONSTRAINT FK_USMS_USER_INST_USER_ID FOREIGN KEY (USER_ID)
REFERENCES USMS_USERS (ID) ON DELETE CASCADE;

ALTER TABLE USMS_USER_INSTITUTION
  ADD CONSTRAINT FK_USMS_USER_INST_INST_ID FOREIGN KEY (INSTITUTION_ID)
REFERENCES USMS_INSTITUTIONS (ID) ON DELETE CASCADE;

ALTER TABLE USMS_USER_ROLE
  ADD CONSTRAINT FK_USMS_USER_ROLE_USER_ID FOREIGN KEY (USER_ID)
REFERENCES USMS_USERS (ID) ON DELETE CASCADE;

ALTER TABLE USMS_USER_ROLE
  ADD CONSTRAINT FK_USMS_USER_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID)
REFERENCES USMS_ROLES (ID) ON DELETE CASCADE;

ALTER TABLE USMS_USER_GRID
  ADD CONSTRAINT FK_USMS_USER_GRID_USER_ID FOREIGN KEY (USER_ID)
REFERENCES USMS_USERS (ID) ON DELETE CASCADE;

-- Create/Recreate unique key constraints
ALTER TABLE USMS_USERS
  ADD CONSTRAINT UN_USMS_USERS_LOGIN_NAME UNIQUE (LOGIN_NAME);

ALTER TABLE USMS_ROLES
  ADD CONSTRAINT UN_USMS_ROLES_NAME UNIQUE (NAME);

ALTER TABLE USMS_APPLICATIONS
  ADD CONSTRAINT USMS_APPLICATIONS_NAME UNIQUE (NAME);

ALTER TABLE USMS_OPERATIONS
  ADD CONSTRAINT USMS_OPERATIONS_NAME UNIQUE (NAME);

ALTER TABLE USMS_INSTITUTIONS
  ADD CONSTRAINT USMS_INSTITUTIONS_NAME UNIQUE (NAME);

ALTER TABLE USMS_PRIVILEGES
  ADD CONSTRAINT USMS_PRIVILEGES UNIQUE (NAME);
