CREATE SEQUENCE GSMP_LOC_GRIDS_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GSMP_LOC_GRID_TYPES_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USMS_INSTITUTIONS_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USMS_APPLICATIONS_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USMS_OPERATIONS_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USMS_PRIVILEGES_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USMS_USERS_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USMS_ROLES_S START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USMS_STAFFS_S START WITH 1 INCREMENT BY 1;
