-- 创建临时表空间
CREATE TEMPORARY TABLESPACE USMS_TEMP
TEMPFILE '/u01/app/oracle/oradata/usms_temp.dbf'
SIZE 32m
AUTOEXTEND ON
NEXT 32m MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL;

-- 创建表空间
CREATE TABLESPACE USMS_DATA
LOGGING
  DATAFILE '/u01/app/oracle/oradata/usms_data.dbf'
SIZE 32m
AUTOEXTEND ON
NEXT 32m MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL;

-- 创建用户
CREATE USER usms IDENTIFIED BY usms123
ACCOUNT UNLOCK
DEFAULT TABLESPACE USMS_DATA
TEMPORARY TABLESPACE USMS_TEMP;

-- 授权限
GRANT CONNECT, RESOURCE TO usms;
