CREATE SEQUENCE GSMP_LOC_GRIDS_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE GSMP_LOC_GRID_TYPES_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USMS_INSTITUTIONS_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USMS_APPLICATIONS_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USMS_OPERATIONS_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USMS_PRIVILEGES_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USMS_USERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USMS_ROLES_SEQ START WITH 1 INCREMENT BY 1;
